import { Role } from "@/types/funcionario";
import type { Funcionario } from "@/types/funcionario";

// TODO: replace with a real Firestore-backed service once funcionarios exist there.
export const mockFuncionarios: Funcionario[] = [
  {
    id: "1",
    name: "Ana Silva",
    email: "ana.silva@example.com",
    telefone: "+55 11 91234-5678",
    age: 34,
    salary: 4500,
    anualSalary: 54000,
    vocationsDay: 12,
    role: Role.GERENTE,
    tipoSanguineo: "O+",
    location: "Unidade Centro",
    isAdmin: true,
  },
  {
    id: "2",
    name: "Bruno Costa",
    email: "bruno.costa@example.com",
    telefone: "+55 11 92345-6789",
    age: 29,
    salary: 3200,
    anualSalary: 38400,
    vocationsDay: 18,
    role: Role.PROFESSOR,
    location: "Unidade Centro",
    manager: "Ana Silva",
    isAdmin: true,
  },
  {
    id: "3",
    name: "Carla Souza",
    email: "carla.souza@example.com",
    telefone: "+55 11 93456-7890",
    age: 26,
    salary: 2800,
    anualSalary: 33600,
    vocationsDay: 20,
    role: Role.ATENDENTE,
    location: "Unidade Zona Sul",
    manager: "Ana Silva",
    isAdmin: false,
  },
  {
    id: "4",
    name: "Diego Almeida",
    email: "diego.almeida@example.com",
    telefone: "+55 11 94567-8901",
    age: 24,
    salary: 2200,
    anualSalary: 26400,
    vocationsDay: 22,
    role: Role.PROFESSOR_TEMPORARIO,
    location: "Unidade Zona Sul",
    manager: "Ana Silva",
    isAdmin: false,
  },
  {
    id: "5",
    name: "Elisa Ferreira",
    email: "elisa.ferreira@example.com",
    telefone: "+55 11 95678-9012",
    age: 41,
    salary: 2100,
    anualSalary: 25200,
    vocationsDay: 15,
    role: Role.FAXINEIRA,
    tipoSanguineo: "A-",
    location: "Unidade Centro",
    manager: "Ana Silva",
    isAdmin: false,
  },
];
